name: Run Prettier
on: [pull_request]

permissions:
  checks: write
  contents: write

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}
      - name: Install dependencies
        run: npm ci 
      - name: Prettier
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          prettier: true